/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author raulv
 */
public class VMain extends javax.swing.JFrame {

    /**
     * Creates new form VMain
     */
    public VMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        bCrear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        bmCrear = new javax.swing.JMenu();
        bmBorrar = new javax.swing.JMenu();
        bmModificar = new javax.swing.JMenu();
        bmPagar = new javax.swing.JMenu();
        bmGenerarJSON = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCrear.setText("jButton1");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bmCrear.setText("Crear");
        bmCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmCrearActionPerformed(evt);
            }
        });
        jMenuBar1.add(bmCrear);

        bmBorrar.setText("Borrar");
        bmBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmBorrarActionPerformed(evt);
            }
        });
        jMenuBar1.add(bmBorrar);

        bmModificar.setText("Modificar");
        bmModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmModificarActionPerformed(evt);
            }
        });
        jMenuBar1.add(bmModificar);

        bmPagar.setText("Pagar");
        bmPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmPagarActionPerformed(evt);
            }
        });
        jMenuBar1.add(bmPagar);

        bmGenerarJSON.setText("Generar JSON");
        bmGenerarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmGenerarJSONActionPerformed(evt);
            }
        });
        jMenuBar1.add(bmGenerarJSON);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCrear)
                .addContainerGap(773, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCrear)
                .addGap(75, 75, 75)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmCrearActionPerformed

    private void bmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmBorrarActionPerformed

    private void bmModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmModificarActionPerformed

    private void bmPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmPagarActionPerformed

    private void bmGenerarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmGenerarJSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmGenerarJSONActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JMenu bmBorrar;
    private javax.swing.JMenu bmCrear;
    private javax.swing.JMenu bmGenerarJSON;
    private javax.swing.JMenu bmModificar;
    private javax.swing.JMenu bmPagar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
